# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(847, 626)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 831, 611))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.clearing = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearing.sizePolicy().hasHeightForWidth())
        self.clearing.setSizePolicy(sizePolicy)
        self.clearing.setMinimumSize(QtCore.QSize(20, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.clearing.setFont(font)
        self.clearing.setObjectName("clearing")
        self.gridLayout.addWidget(self.clearing, 6, 5, 1, 3)
        self.batchaction = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batchaction.sizePolicy().hasHeightForWidth())
        self.batchaction.setSizePolicy(sizePolicy)
        self.batchaction.setMinimumSize(QtCore.QSize(20, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.batchaction.setFont(font)
        self.batchaction.setObjectName("batchaction")
        self.gridLayout.addWidget(self.batchaction, 6, 2, 1, 3)
        self.content = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.content.setFont(font)
        self.content.setAlignment(QtCore.Qt.AlignCenter)
        self.content.setObjectName("content")
        self.gridLayout.addWidget(self.content, 2, 0, 1, 1)
        self.result = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.result.setFont(font)
        self.result.setAlignment(QtCore.Qt.AlignCenter)
        self.result.setObjectName("result")
        self.gridLayout.addWidget(self.result, 4, 0, 1, 1)
        self.contentcontent = QtWidgets.QTextEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.contentcontent.setFont(font)
        self.contentcontent.setObjectName("contentcontent")
        self.gridLayout.addWidget(self.contentcontent, 2, 1, 1, 7)
        self.titlecontent = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.titlecontent.setFont(font)
        self.titlecontent.setObjectName("titlecontent")
        self.gridLayout.addWidget(self.titlecontent, 0, 1, 1, 7)
        self.title = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.title.setFont(font)
        self.title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.gridLayout.addWidget(self.title, 0, 0, 1, 1)
        self.action = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.action.sizePolicy().hasHeightForWidth())
        self.action.setSizePolicy(sizePolicy)
        self.action.setMinimumSize(QtCore.QSize(20, 70))
        self.action.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.action.setFont(font)
        self.action.setIconSize(QtCore.QSize(20, 20))
        self.action.setObjectName("action")
        self.gridLayout.addWidget(self.action, 6, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 5, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 3, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 1, 3, 1, 1)
        self.classification = QtWidgets.QTextBrowser(self.gridLayoutWidget)
        self.classification.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classification.sizePolicy().hasHeightForWidth())
        self.classification.setSizePolicy(sizePolicy)
        self.classification.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.classification.setFont(font)
        self.classification.setObjectName("classification")
        self.gridLayout.addWidget(self.classification, 4, 1, 1, 1)
        self.fscore = QtWidgets.QTextBrowser(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.fscore.setFont(font)
        self.fscore.setObjectName("fscore")
        self.gridLayout.addWidget(self.fscore, 4, 2, 1, 6)
        spacerItem3 = QtWidgets.QSpacerItem(160, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "新闻文本分类器"))
        self.clearing.setText(_translate("MainWindow", "清空"))
        self.batchaction.setText(_translate("MainWindow", "批量运行"))
        self.content.setText(_translate("MainWindow", "新闻内容"))
        self.result.setText(_translate("MainWindow", "分类结果"))
        self.title.setText(_translate("MainWindow", "新闻标题"))
        self.action.setText(_translate("MainWindow", "运行"))

